# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Logic App Infrastructure as Code Pipeline. 

on:
  - workflow_dispatch 

env:
  AZURE_LOGICAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.301'    # set this to the dotnet version to use
  RG_LA: 'GHApp'
  RG_CON: 'GHConnections'

jobs:
  deploy-all: 
    runs-on: ubuntu-latest
    steps:
                      
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        enable-AzPSSession: true 

    # Checkout
    - name: Checkout
      uses: actions/checkout@v1

    # Deployment of template  

    - name: Deploy Logic App Resources
      uses: Azure/arm-deploy@v1.0.1
      id: ladeploy
      with:
        # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP
        scope: resourcegroup  
        subscriptionId: ${{ secrets.AZURE_SUB }}
        resourceGroupName:  ${{ env.RG_LA }}
        template: ARM/la-template.json  # Set this to the location of your template file
        parameters: ARM/la-parameters.json # Set this to the location of your parameters file
        deploymentMode: Incremental
   
    # Deployment of template    
    - name: Deploy Connector Resources 
      id: msdemoconn
      uses: Azure/arm-deploy@v1.0.1
      with:
        scope: resourcegroup  
        subscriptionId: ${{ secrets.AZURE_SUB }}
        resourceGroupName: ${{ env.RG_CON }}
        template: ARM/connectors-template.json  # Set this to the location of your template file
        parameters: ARM/connectors-parameters.json logicAppSystemAssignedIdentityTenantId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityTenantId }} logicAppSystemAssignedIdentityObjectId=${{ steps.ladeploy.outputs.logicAppSystemAssignedIdentityObjectId }}
        deploymentMode: Incremental

   